
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class İzinFormu extends javax.swing.JFrame {
    DefaultTableModel model;
    OgrenciIslemleri islemler = new OgrenciIslemleri();
    /**
     * Creates new form İzinFormu
     */
    public İzinFormu(java.awt.Frame parent, boolean modal) {
        super();
        initComponents();
        model = (DefaultTableModel)izin_al_tablo.getModel();
        OgrenciGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        izin_formu_geri = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        izin_al_tablo = new javax.swing.JTable();
        tarih_alani = new javax.swing.JTextField();
        sure_alani = new javax.swing.JTextField();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        telefon_alani = new javax.swing.JTextField();
        izin_al = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        İzin_formu_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("İzin Formu");
        setLocation(new java.awt.Point(400, 150));

        jPanel1.setLayout(null);

        izin_formu_geri.setBackground(new java.awt.Color(255, 255, 255));
        izin_formu_geri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        izin_formu_geri.setForeground(new java.awt.Color(0, 51, 255));
        izin_formu_geri.setText("GERİ");
        izin_formu_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izin_formu_geriActionPerformed(evt);
            }
        });
        jPanel1.add(izin_formu_geri);
        izin_formu_geri.setBounds(440, 520, 200, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ÇIKIŞ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 570, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 90, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 130, 100, 30);

        ad_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ad_alani);
        ad_alani.setBounds(290, 90, 150, 30);

        soyad_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(soyad_alani);
        soyad_alani.setBounds(290, 130, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("İzin Tarihi :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(690, 100, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("İzin Süresi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(690, 150, 110, 30);

        izin_al_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SIRA", "AD", "SOYAD", "TELEFON", "İZİN TARİHİ(gg.aa.yy)", "İZİN SÜRESİ(gg)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        izin_al_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izin_al_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(izin_al_tablo);
        if (izin_al_tablo.getColumnModel().getColumnCount() > 0) {
            izin_al_tablo.getColumnModel().getColumn(0).setResizable(false);
            izin_al_tablo.getColumnModel().getColumn(1).setResizable(false);
            izin_al_tablo.getColumnModel().getColumn(2).setResizable(false);
            izin_al_tablo.getColumnModel().getColumn(3).setResizable(false);
            izin_al_tablo.getColumnModel().getColumn(4).setResizable(false);
            izin_al_tablo.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 240, 760, 210);

        tarih_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(tarih_alani);
        tarih_alani.setBounds(790, 100, 150, 30);

        sure_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sure_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sure_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(sure_alani);
        sure_alani.setBounds(790, 150, 150, 30);

        arama_cubugu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });
        jPanel1.add(arama_cubugu);
        arama_cubugu.setBounds(180, 20, 760, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(180, 70, 760, 2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefon :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 170, 70, 30);

        telefon_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(telefon_alani);
        telefon_alani.setBounds(290, 170, 150, 30);

        izin_al.setBackground(new java.awt.Color(255, 255, 255));
        izin_al.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        izin_al.setForeground(new java.awt.Color(0, 204, 0));
        izin_al.setText("İZİN AL");
        izin_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izin_alActionPerformed(evt);
            }
        });
        jPanel1.add(izin_al);
        izin_al.setBounds(440, 470, 200, 30);

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(mesaj_yazisi);
        mesaj_yazisi.setBounds(290, 204, 500, 30);

        İzin_formu_arkaplan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        İzin_formu_arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        İzin_formu_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-background-13.jpg"))); // NOI18N
        jPanel1.add(İzin_formu_arkaplan);
        İzin_formu_arkaplan.setBounds(0, 0, 1110, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izin_formu_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izin_formu_geriActionPerformed
        ogrenci_yurt_islemi oyislem = new ogrenci_yurt_islemi();
        setVisible(false);
        oyislem.setVisible(true);
    }//GEN-LAST:event_izin_formu_geriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void sure_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sure_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sure_alaniActionPerformed

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void izin_al_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izin_al_tabloMouseClicked
        int selectedrow = izin_al_tablo.getSelectedRow();
        ad_alani.setText(model.getValueAt(selectedrow, 1).toString());
        soyad_alani.setText(model.getValueAt(selectedrow, 2).toString());
        telefon_alani.setText(model.getValueAt(selectedrow, 3).toString());
        tarih_alani.setText(model.getValueAt(selectedrow, 4).toString());
        sure_alani.setText(model.getValueAt(selectedrow, 5).toString());
        
    }//GEN-LAST:event_izin_al_tabloMouseClicked

    private void izin_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izin_alActionPerformed
        mesaj_yazisi.setText("");
        
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String telefon = telefon_alani.getText();
        String tarih = tarih_alani.getText();
        String sure = sure_alani.getText();
        
        islemler.ogrenciİzin(ad, soyad, telefon, tarih, sure);
        OgrenciGoruntule();
        mesaj_yazisi.setText("İzin Kaydı Sisteme Giriliyor...");
        
    }//GEN-LAST:event_izin_alActionPerformed
    public void OgrenciGoruntule(){
        model.setRowCount(0);
        ArrayList<Ogrenciİzin> proje = new ArrayList<Ogrenciİzin>();
        
        proje = islemler.İzinOgrenciGetir();
        if(proje !=null){
            for(Ogrenciİzin ogrenci : proje){
                Object[] eklenecek = {ogrenci.getSira(),ogrenci.getAd(),ogrenci.getSoyad(),ogrenci.getTelefon(),ogrenci.getIzin_tarihi(),ogrenci.getIzin_suresi()};
                model.addRow(eklenecek);
            }
        } 
    }
    /**
     * @param args the command line arguments
     */
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    
        izin_al_tablo.setRowSorter(tr);
    
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(İzinFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(İzinFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(İzinFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(İzinFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                İzinFormu dialog = new İzinFormu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField ad_alani;
    javax.swing.JTextField arama_cubugu;
    javax.swing.JButton izin_al;
    javax.swing.JTable izin_al_tablo;
    javax.swing.JButton izin_formu_geri;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JLabel mesaj_yazisi;
    javax.swing.JTextField soyad_alani;
    javax.swing.JTextField sure_alani;
    javax.swing.JTextField tarih_alani;
    javax.swing.JTextField telefon_alani;
    javax.swing.JLabel İzin_formu_arkaplan;
    // End of variables declaration//GEN-END:variables
}
