
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Ogrenci_ara extends javax.swing.JFrame {
    DefaultTableModel model;
    OgrenciIslemleri islemler = new OgrenciIslemleri();
    /**
     * Creates new form Ogrenci_ara
     */
    public Ogrenci_ara(java.awt.Frame parent, boolean modal) {
        super();
        initComponents();
        model = (DefaultTableModel)ogrenci_ara_tablo.getModel();
        OgrenciGoruntule();
    }

    Ogrenci_ara() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        arama_cubugu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenci_ara_tablo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ogrenci_ara_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Öğrenci Arama");
        setLocation(new java.awt.Point(600, 300));

        jPanel1.setLayout(null);

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });
        jPanel1.add(arama_cubugu);
        arama_cubugu.setBounds(80, 30, 580, 30);

        ogrenci_ara_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra", "Ad", "Soyad", "Blok", "Kat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ogrenci_ara_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ogrenci_ara_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ogrenci_ara_tablo);
        if (ogrenci_ara_tablo.getColumnModel().getColumnCount() > 0) {
            ogrenci_ara_tablo.getColumnModel().getColumn(0).setResizable(false);
            ogrenci_ara_tablo.getColumnModel().getColumn(1).setResizable(false);
            ogrenci_ara_tablo.getColumnModel().getColumn(2).setResizable(false);
            ogrenci_ara_tablo.getColumnModel().getColumn(3).setResizable(false);
            ogrenci_ara_tablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 580, 210);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 340, 190, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ÇIKIŞ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 380, 190, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(80, 80, 580, 0);

        ogrenci_ara_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ogrenci_yurt_islemleri.jpg"))); // NOI18N
        jPanel1.add(ogrenci_ara_arkaplan);
        ogrenci_ara_arkaplan.setBounds(0, 0, 730, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ogrenci_yurt_islemi oyislem = new ogrenci_yurt_islemi();
        setVisible(false);
        oyislem.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ogrenci_ara_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ogrenci_ara_tabloMouseClicked

    }//GEN-LAST:event_ogrenci_ara_tabloMouseClicked

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        
    }//GEN-LAST:event_arama_cubuguActionPerformed
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    
        ogrenci_ara_tablo.setRowSorter(tr);
    
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    /**
     * @param args the command line arguments
     */
    public void OgrenciGoruntule(){
        model.setRowCount(0);
        ArrayList<Ogrenci> proje = new ArrayList<Ogrenci>();
        
        proje = islemler.araOgrencileriGetir();
        if(proje !=null){
            for(Ogrenci ogrenci : proje){
                Object[] eklenecek = {ogrenci.getSira(),ogrenci.getAd(),ogrenci.getSoyad(),ogrenci.getKat(),ogrenci.getOda()};
                model.addRow(eklenecek);
            }
        }     
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ogrenci_ara dialog = new Ogrenci_ara(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField arama_cubugu;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JLabel ogrenci_ara_arkaplan;
    javax.swing.JTable ogrenci_ara_tablo;
    // End of variables declaration//GEN-END:variables
}
