/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Memonun Tulparı
 */
public class ogrenci_yurt_islemi extends javax.swing.JFrame {
    OgrenciIslemleri islemler = new OgrenciIslemleri();
    /**
     * Creates new form ogrenci_yurt_islemi
     */
    public ogrenci_yurt_islemi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        izin_formu_alani = new javax.swing.JButton();
        ogrenci_ara_islemler = new javax.swing.JButton();
        a_blok_giris_alani = new javax.swing.JButton();
        b_blok_giris_alani = new javax.swing.JButton();
        cıkıs = new javax.swing.JButton();
        oyislem_alan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ogrenci_yurt_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Öğrenci - Yurt İşlemleri");
        setLocation(new java.awt.Point(600, 300));

        jPanel1.setLayout(null);

        izin_formu_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        izin_formu_alani.setText("İZİN FORMU");
        izin_formu_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izin_formu_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(izin_formu_alani);
        izin_formu_alani.setBounds(70, 130, 260, 40);

        ogrenci_ara_islemler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ogrenci_ara_islemler.setText("ÖĞRENCİ ARA");
        ogrenci_ara_islemler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_ara_islemlerActionPerformed(evt);
            }
        });
        jPanel1.add(ogrenci_ara_islemler);
        ogrenci_ara_islemler.setBounds(420, 130, 260, 40);

        a_blok_giris_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a_blok_giris_alani.setText("A BLOK GİRİŞ");
        a_blok_giris_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_blok_giris_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(a_blok_giris_alani);
        a_blok_giris_alani.setBounds(70, 250, 260, 40);

        b_blok_giris_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_blok_giris_alani.setText("B BLOK GİRİŞ");
        b_blok_giris_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_blok_giris_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(b_blok_giris_alani);
        b_blok_giris_alani.setBounds(420, 250, 260, 40);

        cıkıs.setBackground(new java.awt.Color(255, 0, 51));
        cıkıs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cıkıs.setForeground(new java.awt.Color(255, 255, 255));
        cıkıs.setText("ÇIKIŞ");
        cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısActionPerformed(evt);
            }
        });
        jPanel1.add(cıkıs);
        cıkıs.setBounds(280, 370, 190, 30);

        oyislem_alan.setBackground(new java.awt.Color(255, 255, 255));
        oyislem_alan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oyislem_alan.setForeground(new java.awt.Color(51, 51, 255));
        oyislem_alan.setText("GERİ");
        oyislem_alan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyislem_alanActionPerformed(evt);
            }
        });
        jPanel1.add(oyislem_alan);
        oyislem_alan.setBounds(280, 320, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LÜTFEN YAPMAK İSTEDİĞİNİZ İŞLEMİ SEÇİNİZ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 0, 600, 70);

        ogrenci_yurt_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ogrenci_yurt_islemleri.jpg"))); // NOI18N
        jPanel1.add(ogrenci_yurt_arkaplan);
        ogrenci_yurt_arkaplan.setBounds(0, 0, 738, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_blok_giris_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_blok_giris_alaniActionPerformed
        B_Blok bblok = new B_Blok();
        setVisible(false);
        bblok.setVisible(true);
    }//GEN-LAST:event_b_blok_giris_alaniActionPerformed

    private void a_blok_giris_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_blok_giris_alaniActionPerformed
        A_blok ablok = new A_blok();
        setVisible(false);
        ablok.setVisible(true);
    }//GEN-LAST:event_a_blok_giris_alaniActionPerformed

    private void cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cıkısActionPerformed

    private void oyislem_alanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyislem_alanActionPerformed
        BlokSec bloksec = new BlokSec();
        setVisible(false);
        bloksec.setVisible(true);
    }//GEN-LAST:event_oyislem_alanActionPerformed

    private void ogrenci_ara_islemlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_ara_islemlerActionPerformed
       Ogrenci_ara ara = new Ogrenci_ara(this, rootPaneCheckingEnabled);
        setVisible(false);
        ara.setVisible(true);
       
    }//GEN-LAST:event_ogrenci_ara_islemlerActionPerformed

    private void izin_formu_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izin_formu_alaniActionPerformed

        İzinFormu giris = new İzinFormu(this, rootPaneCheckingEnabled);
        setVisible(false);
        giris.setVisible(true);
    }//GEN-LAST:event_izin_formu_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenci_yurt_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenci_yurt_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenci_yurt_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenci_yurt_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogrenci_yurt_islemi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton a_blok_giris_alani;
    javax.swing.JButton b_blok_giris_alani;
    javax.swing.JButton cıkıs;
    javax.swing.JButton izin_formu_alani;
    javax.swing.JLabel jLabel1;
    javax.swing.JPanel jPanel1;
    javax.swing.JButton ogrenci_ara_islemler;
    javax.swing.JLabel ogrenci_yurt_arkaplan;
    javax.swing.JButton oyislem_alan;
    // End of variables declaration//GEN-END:variables
}
